---
name: Effective Java Study Issue
about: Effective Java 스터디 아이템 정리
title: "[아이템 번호] 아이템 제목"
labels: study
assignees: ''
---

# 📌 [아이템 번호] 아이템 제목

## ✨ 핵심 내용
- 해당 아이템에서 가장 중요한 개념을 정리해주세요.
- 예제 코드가 있다면 포함해주세요.

## 💡 새롭게 알게 된 점
- 학습하면서 이전과 다르게 이해한 점이나 새롭게 알게 된 개념을 공유해주세요.

## 📚 정리
- 핵심 내용을 정리해주세요.
- 해당 개념을 실제 프로젝트에서 어떻게 활용할 수 있을지 아이디어를 공유해주시면 더 좋아요!

---

📢 댓글로 각자의 학습 내용을 공유해주세요!
